# Generated by Django 4.0.4 on 2022-06-27 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ganador', models.IntegerField(max_length=18)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subastas_app.articulo')),
                ('user_ganador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
