# Generated by Django 4.0.4 on 2022-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_app', '0002_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='precio_ganador',
            field=models.IntegerField(),
        ),
    ]
