# Generated by Django 4.0.4 on 2022-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_app', '0004_alter_subasta_precio_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/user_images/anonimo.svg', null=True, upload_to='user_images'),
        ),
    ]
