# Generated by Django 4.0.4 on 2022-07-02 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_app', '0004_alter_articulo_categoria_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='user_ganador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
